services:
  migrate-client:
    image: migrate-client
    build:
      context: .
      dockerfile: ./Dockerfiles/prod.Dockerfile
    container_name: migrate-client
    env_file:
      - ./.env/.local/.app.env
    networks:
      - migrate-network
    ports:
      - 8001:80
      - 8443:443
    volumes:
#      - .:/app
      - ${HOME}/.dev-certs/:/https
      - /mnt/mailboxes:/home/mailboxes/
    dns:
      - 8.8.8.8
    depends_on:
      - uploader-redis
        
  uploader-redis:
    image: redis
    container_name: uploader-redis
    hostname: uploader-redis
    volumes:
      - uploader-redis-data:/data
    ports:
      - 6380:6379
    networks:
      - migrate-network

networks:
  migrate-network:
    
volumes:
  uploader-redis-data:

    

    
