services:
  migrate-client:
    image: dreg.knust.edu.gh/mi-asp:0.0.1
    container_name: migrate-client
    networks:
      - migrate-network
    ports:
      - 8001:80
      - 8443:443
    volumes:
      - /mnt/migrate/certificates/:/https
      - /mnt/migrate/mailboxes:/home/mailboxes/
    dns:
      - 8.8.8.8
    depends_on:
      - uploader-redis
    env_file:
      - .env
  
  uploader-redis:
    image: redis
    container_name: uploader-redis
    hostname: uploader-redis
    volumes:
      - uploader-redis-data:/data
    ports:
      - 6380:6379
    networks:
      - migrate-network

networks:
  migrate-network:

volumes:
  uploader-redis-data:

    

    
